var annotated_dup =
[
    [ "dynamix", null, [
      [ "combinators", null, [
        [ "boolean_and", "classdynamix_1_1combinators_1_1boolean__and.html", "classdynamix_1_1combinators_1_1boolean__and" ],
        [ "boolean_or", "classdynamix_1_1combinators_1_1boolean__or.html", "classdynamix_1_1combinators_1_1boolean__or" ],
        [ "mean", "classdynamix_1_1combinators_1_1mean.html", "classdynamix_1_1combinators_1_1mean" ],
        [ "sum", "classdynamix_1_1combinators_1_1sum.html", "classdynamix_1_1combinators_1_1sum" ]
      ] ],
      [ "internal", null, [
        [ "default_allocator", "classdynamix_1_1internal_1_1default__allocator.html", "classdynamix_1_1internal_1_1default__allocator" ],
        [ "deprecated_mixin_impl", "classdynamix_1_1internal_1_1deprecated__mixin__impl.html", "classdynamix_1_1internal_1_1deprecated__mixin__impl" ],
        [ "domain", "classdynamix_1_1internal_1_1domain.html", "classdynamix_1_1internal_1_1domain" ],
        [ "feature_instance", "structdynamix_1_1internal_1_1feature__instance.html", null ],
        [ "feature_parser", "classdynamix_1_1internal_1_1feature__parser.html", "classdynamix_1_1internal_1_1feature__parser" ],
        [ "feature_registrator", "classdynamix_1_1internal_1_1feature__registrator.html", "classdynamix_1_1internal_1_1feature__registrator" ],
        [ "has_set_num_results", "structdynamix_1_1internal_1_1has__set__num__results.html", null ],
        [ "mandatory_mixin_impl", "classdynamix_1_1internal_1_1mandatory__mixin__impl.html", "classdynamix_1_1internal_1_1mandatory__mixin__impl" ],
        [ "message_feature_tag", "structdynamix_1_1internal_1_1message__feature__tag.html", null ],
        [ "message_for_mixin", "structdynamix_1_1internal_1_1message__for__mixin.html", "structdynamix_1_1internal_1_1message__for__mixin" ],
        [ "message_perks", "structdynamix_1_1internal_1_1message__perks.html", "structdynamix_1_1internal_1_1message__perks" ],
        [ "message_registrator", "structdynamix_1_1internal_1_1message__registrator.html", "structdynamix_1_1internal_1_1message__registrator" ],
        [ "message_t", "structdynamix_1_1internal_1_1message__t.html", "structdynamix_1_1internal_1_1message__t" ],
        [ "message_wrapper", "structdynamix_1_1internal_1_1message__wrapper.html", null ],
        [ "mixin_data_in_object", "classdynamix_1_1internal_1_1mixin__data__in__object.html", "classdynamix_1_1internal_1_1mixin__data__in__object" ],
        [ "mixin_name_feature", "structdynamix_1_1internal_1_1mixin__name__feature.html", "structdynamix_1_1internal_1_1mixin__name__feature" ],
        [ "mixin_type_info", "classdynamix_1_1internal_1_1mixin__type__info.html", "classdynamix_1_1internal_1_1mixin__type__info" ],
        [ "mixin_type_info_instance", "structdynamix_1_1internal_1_1mixin__type__info__instance.html", "structdynamix_1_1internal_1_1mixin__type__info__instance" ],
        [ "msg_caller", "structdynamix_1_1internal_1_1msg__caller.html", "structdynamix_1_1internal_1_1msg__caller" ],
        [ "msg_multicast", "structdynamix_1_1internal_1_1msg__multicast.html", "structdynamix_1_1internal_1_1msg__multicast" ],
        [ "msg_unicast", "structdynamix_1_1internal_1_1msg__unicast.html", "structdynamix_1_1internal_1_1msg__unicast" ],
        [ "noop_feature_t", "structdynamix_1_1internal_1_1noop__feature__t.html", null ],
        [ "object_mutator", "classdynamix_1_1internal_1_1object__mutator.html", "classdynamix_1_1internal_1_1object__mutator" ],
        [ "object_type_info", "classdynamix_1_1internal_1_1object__type__info.html", "classdynamix_1_1internal_1_1object__type__info" ],
        [ "substitute_mixin_impl", "classdynamix_1_1internal_1_1substitute__mixin__impl.html", "classdynamix_1_1internal_1_1substitute__mixin__impl" ]
      ] ],
      [ "bad_copy_assignment", "classdynamix_1_1bad__copy__assignment.html", null ],
      [ "bad_copy_construction", "classdynamix_1_1bad__copy__construction.html", null ],
      [ "bad_message_call", "classdynamix_1_1bad__message__call.html", null ],
      [ "bad_mixin_move", "classdynamix_1_1bad__mixin__move.html", null ],
      [ "bad_mutation", "classdynamix_1_1bad__mutation.html", null ],
      [ "bad_mutation_source", "classdynamix_1_1bad__mutation__source.html", null ],
      [ "bad_next_bidder_call", "classdynamix_1_1bad__next__bidder__call.html", null ],
      [ "basic_mixin_type_info", "classdynamix_1_1basic__mixin__type__info.html", "classdynamix_1_1basic__mixin__type__info" ],
      [ "bundled_mixins", "classdynamix_1_1bundled__mixins.html", "classdynamix_1_1bundled__mixins" ],
      [ "dependent_mixins", "classdynamix_1_1dependent__mixins.html", "classdynamix_1_1dependent__mixins" ],
      [ "deprecated_mixin", "classdynamix_1_1deprecated__mixin.html", "classdynamix_1_1deprecated__mixin" ],
      [ "domain_allocator", "classdynamix_1_1domain__allocator.html", "classdynamix_1_1domain__allocator" ],
      [ "exception", "classdynamix_1_1exception.html", null ],
      [ "feature", "classdynamix_1_1feature.html", "classdynamix_1_1feature" ],
      [ "mandatory_mixin", "classdynamix_1_1mandatory__mixin.html", "classdynamix_1_1mandatory__mixin" ],
      [ "mixin_allocator", "classdynamix_1_1mixin__allocator.html", "classdynamix_1_1mixin__allocator" ],
      [ "mixin_collection", "classdynamix_1_1mixin__collection.html", "classdynamix_1_1mixin__collection" ],
      [ "mutation_rule", "classdynamix_1_1mutation__rule.html", "classdynamix_1_1mutation__rule" ],
      [ "mutually_exclusive_mixins", "classdynamix_1_1mutually__exclusive__mixins.html", "classdynamix_1_1mutually__exclusive__mixins" ],
      [ "no_features_t", "structdynamix_1_1no__features__t.html", null ],
      [ "object", "classdynamix_1_1object.html", "classdynamix_1_1object" ],
      [ "object_allocator", "classdynamix_1_1object__allocator.html", "classdynamix_1_1object__allocator" ],
      [ "object_type_mutation", "classdynamix_1_1object__type__mutation.html", "classdynamix_1_1object__type__mutation" ],
      [ "object_type_template", "classdynamix_1_1object__type__template.html", "classdynamix_1_1object__type__template" ],
      [ "same_type_mutator", "classdynamix_1_1same__type__mutator.html", "classdynamix_1_1same__type__mutator" ],
      [ "single_object_mutator", "classdynamix_1_1single__object__mutator.html", "classdynamix_1_1single__object__mutator" ],
      [ "substitute_mixin", "classdynamix_1_1substitute__mixin.html", "classdynamix_1_1substitute__mixin" ],
      [ "unicast_clash", "classdynamix_1_1unicast__clash.html", null ]
    ] ]
];